service: cognito-github-oidc

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x

functions:
  authorize:
    handler: handler.authorize
    events:
      - http:
          path: authorize
          method: get
  token:
    handler: handler.token
    environment:
      PRIVATE_KEY: ${file(keys/cognito-github-oidc.key)}
    events:
      - http:
          path: token
          method: post
  jwks:
    handler: handler.jwks
    environment:
      PUBLIC_KEY: ${file(keys/cognito-github-oidc.key.pub)}
    events:
      - http:
          path: jwks
          method: get
  auth_callback:
    handler: handler.auth_callback
    events:
      - http:
          path: auth_callback
          method: get

  userinfo:
    handler: handler.userinfo
    events:
      - http:
          path: userinfo
          method: get
