service: cognito-github-oidc

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x

functions:
  authorize:
    handler: handler.authorize
    events:
      - http:
          path: authorize
          method: get
  token:
    handler: handler.token
    events:
      - http:
          path: token
          method: post
  auth_callback:
    handler: handler.auth_callback
    events:
      - http:
          path: auth_callback
          method: get
